//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovoi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataBaseEntities : DbContext
    {
        private static DataBaseEntities _context;
        public DataBaseEntities()
            : base("name=DataBaseEntities")
        {
        }
        public static DataBaseEntities GetContext()
        {
            if (_context == null)
                _context = new DataBaseEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CompanyPostavshiki> CompanyPostavshiki { get; set; }
        public virtual DbSet<EdinicyIzmereniya> EdinicyIzmereniya { get; set; }
        public virtual DbSet<MaterialyIFurnitura> MaterialyIFurnitura { get; set; }
        public virtual DbSet<OformlenieZakaza> OformlenieZakaza { get; set; }
        public virtual DbSet<Polzovateli> Polzovateli { get; set; }
        public virtual DbSet<PostuplenieTovara> PostuplenieTovara { get; set; }
        public virtual DbSet<PostuplenieTovara_Soderzhimoe> PostuplenieTovara_Soderzhimoe { get; set; }
        public virtual DbSet<Roli> Roli { get; set; }
        public virtual DbSet<Sborka> Sborka { get; set; }
        public virtual DbSet<Sborka_Materialy> Sborka_Materialy { get; set; }
        public virtual DbSet<Specifikaciya_Materialy> Specifikaciya_Materialy { get; set; }
        public virtual DbSet<SpecifikaciyaNaIzdelie> SpecifikaciyaNaIzdelie { get; set; }
        public virtual DbSet<SpisokZakazov> SpisokZakazov { get; set; }
        public virtual DbSet<StatusyZakazov> StatusyZakazov { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TipyMaterialov> TipyMaterialov { get; set; }
        public virtual DbSet<Zakazchiki> Zakazchiki { get; set; }
    }
}
