//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovoi
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialyIFurnitura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MaterialyIFurnitura()
        {
            this.PostuplenieTovara_Soderzhimoe = new HashSet<PostuplenieTovara_Soderzhimoe>();
            this.Sborka_Materialy = new HashSet<Sborka_Materialy>();
            this.Specifikaciya_Materialy = new HashSet<Specifikaciya_Materialy>();
        }
    
        public int Id_MaterialyIFurnitura { get; set; }
        public string Name_MaterialyIFurnitura { get; set; }
        public string Artikul { get; set; }
        public int Id_TipyMaterialov { get; set; }
        public int Id_Edinicylzmereniya { get; set; }
    
        public virtual EdinicyIzmereniya EdinicyIzmereniya { get; set; }
        public virtual TipyMaterialov TipyMaterialov { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostuplenieTovara_Soderzhimoe> PostuplenieTovara_Soderzhimoe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sborka_Materialy> Sborka_Materialy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Specifikaciya_Materialy> Specifikaciya_Materialy { get; set; }
    }
}
