//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovoi
{
    using System;
    using System.Collections.Generic;
    
    public partial class OformlenieZakaza
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OformlenieZakaza()
        {
            this.Sborka = new HashSet<Sborka>();
            this.Sborka1 = new HashSet<Sborka>();
            this.SpecifikaciyaNaIzdelie = new HashSet<SpecifikaciyaNaIzdelie>();
            this.SpisokZakazov = new HashSet<SpisokZakazov>();
        }
    
        public int Id_OformlenieZakaza { get; set; }
        public System.DateTime DataOformlenieZakaza { get; set; }
        public string NaimenovanieZakaza { get; set; }
        public int Zakazchik_OformlenieZakaza { get; set; }
        public string OpisanieIzdeliya { get; set; }
        public string RazmeriGotovogoIzdeliya { get; set; }
        public string Dokumentaciya { get; set; }
    
        public virtual Zakazchiki Zakazchiki { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sborka> Sborka { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sborka> Sborka1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpecifikaciyaNaIzdelie> SpecifikaciyaNaIzdelie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpisokZakazov> SpisokZakazov { get; set; }
    }
}
