//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovoi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Polzovateli
    {
        public int Id_Polzovatel { get; set; }
        public string ImyaPolzovatelya { get; set; }
        public string FamiliyaPolzovatelia { get; set; }
        public string OtchestvoPolzovatelia { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public int Id_Roli { get; set; }
    
        public virtual Roli Roli { get; set; }
    }
}
