//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovoi
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostuplenieTovara_Soderzhimoe
    {
        public int Id_PostuplenieTovara_Soderzhimoe { get; set; }
        public int Id_Postupleniya { get; set; }
        public int Id_Materiala { get; set; }
        public int Kolichestvo_Postuplenie { get; set; }
        public decimal Cena { get; set; }
        public decimal Summa { get; set; }
    
        public virtual MaterialyIFurnitura MaterialyIFurnitura { get; set; }
        public virtual PostuplenieTovara PostuplenieTovara { get; set; }
    }
}
