//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovoi
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostuplenieTovara
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PostuplenieTovara()
        {
            this.PostuplenieTovara_Soderzhimoe = new HashSet<PostuplenieTovara_Soderzhimoe>();
        }
    
        public int Id_PostuplenieTovara { get; set; }
        public System.DateTime DataPostupleniya { get; set; }
        public int CompaniyaPostavshika { get; set; }
        public string Dogovor { get; set; }
    
        public virtual CompanyPostavshiki CompanyPostavshiki { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostuplenieTovara_Soderzhimoe> PostuplenieTovara_Soderzhimoe { get; set; }
    }
}
