//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovoi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sborka_Materialy
    {
        public int Id_Sborka_Materialy { get; set; }
        public int Id_Sborka { get; set; }
        public int Id_Material { get; set; }
        public int Kolichestvo_SborkaMaterialy { get; set; }
    
        public virtual MaterialyIFurnitura MaterialyIFurnitura { get; set; }
        public virtual Sborka Sborka { get; set; }
    }
}
