//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovoi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sborka
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sborka()
        {
            this.Sborka_Materialy = new HashSet<Sborka_Materialy>();
        }
    
        public int Id_Sborka { get; set; }
        public int Id_Zakaza { get; set; }
        public System.DateTime DataSozdaniyaSborki { get; set; }
    
        public virtual OformlenieZakaza OformlenieZakaza { get; set; }
        public virtual OformlenieZakaza OformlenieZakaza1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sborka_Materialy> Sborka_Materialy { get; set; }
    }
}
