//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovoi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specifikaciya_Materialy
    {
        public int Id_Specifikaciya_Materialy { get; set; }
        public int Id_Specifikaciya { get; set; }
        public int Id_Materiala { get; set; }
        public int Kolichestvo_SpecifikaciyaMaterialy { get; set; }
    
        public virtual MaterialyIFurnitura MaterialyIFurnitura { get; set; }
        public virtual SpecifikaciyaNaIzdelie SpecifikaciyaNaIzdelie { get; set; }
    }
}
