//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovoi
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecifikaciyaNaIzdelie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SpecifikaciyaNaIzdelie()
        {
            this.Specifikaciya_Materialy = new HashSet<Specifikaciya_Materialy>();
        }
    
        public int Id_SpecifikaciyaNaIzdelie { get; set; }
        public int Id_Zakaza { get; set; }
        public System.DateTime DataSozdaniyaSpecifikacii { get; set; }
        public int Zakazchik { get; set; }
    
        public virtual OformlenieZakaza OformlenieZakaza { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Specifikaciya_Materialy> Specifikaciya_Materialy { get; set; }
        public virtual SpisokZakazov SpisokZakazov { get; set; }
        public virtual Zakazchiki Zakazchiki { get; set; }
    }
}
