//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovoi
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpisokZakazov
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SpisokZakazov()
        {
            this.SpecifikaciyaNaIzdelie = new HashSet<SpecifikaciyaNaIzdelie>();
        }
    
        public int Id_SpiskaZakazov { get; set; }
        public int Status { get; set; }
        public System.DateTime DataZakaza { get; set; }
        public int NomerZakaza { get; set; }
        public int Zakazchik_SpisokZakazov { get; set; }
    
        public virtual OformlenieZakaza OformlenieZakaza { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpecifikaciyaNaIzdelie> SpecifikaciyaNaIzdelie { get; set; }
        public virtual StatusyZakazov StatusyZakazov { get; set; }
        public virtual Zakazchiki Zakazchiki { get; set; }
    }
}
