//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovoi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakazchiki
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zakazchiki()
        {
            this.OformlenieZakaza = new HashSet<OformlenieZakaza>();
            this.SpecifikaciyaNaIzdelie = new HashSet<SpecifikaciyaNaIzdelie>();
            this.SpisokZakazov = new HashSet<SpisokZakazov>();
        }
    
        public int Id_Zakazchika { get; set; }
        public string FamiliyaZakazchika { get; set; }
        public string ImyaZakazchika { get; set; }
        public string OtchestvoZakazchika { get; set; }
        public string TelefoneZakazchika { get; set; }
        public string EmailZakazchika { get; set; }
        public string AdresProjivaniya { get; set; }
        public string FullName
        {
            get
            {
                return $"{FamiliyaZakazchika} {ImyaZakazchika} {OtchestvoZakazchika}";
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OformlenieZakaza> OformlenieZakaza { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpecifikaciyaNaIzdelie> SpecifikaciyaNaIzdelie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpisokZakazov> SpisokZakazov { get; set; }
    }
}
